#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Erp")]
public partial class DataClasses3DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Définitions de méthodes d'extensibilité
  partial void OnCreated();
  partial void InsertContact(Contact instance);
  partial void UpdateContact(Contact instance);
  partial void DeleteContact(Contact instance);
  #endregion
	
	public DataClasses3DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ErpConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses3DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses3DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses3DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses3DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Contact> Contact
	{
		get
		{
			return this.GetTable<Contact>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AjouterContact")]
	public int AjouterContact([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string prenom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string civilite, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telephone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string fonction, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_entreprise)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, prenom, civilite, telephone, fax, email, fonction, id_entreprise);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteContact")]
	public int DeleteContact([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_contact)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_contact);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetContactsByID")]
	public ISingleResult<GetContactsByIDResult> GetContactsByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_contact)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_contact);
		return ((ISingleResult<GetContactsByIDResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetContactsByIDEnt")]
	public ISingleResult<GetContactsByIDEntResult> GetContactsByIDEnt([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_entreprise)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_entreprise);
		return ((ISingleResult<GetContactsByIDEntResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectContacts")]
	public ISingleResult<SelectContactsResult> SelectContacts()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<SelectContactsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateContacts")]
	public int UpdateContacts([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string prenom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string civilite, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telephone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string fonction, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_entreprise, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_contact)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, prenom, civilite, telephone, fax, email, fonction, id_entreprise, id_contact);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contact")]
public partial class Contact : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_contact;
	
	private string _nom;
	
	private string _prenom;
	
	private string _civilite;
	
	private System.Nullable<int> _telephone;
	
	private System.Nullable<int> _fax;
	
	private string _email;
	
	private string _fonction;
	
	private System.Nullable<int> _id_entreprise;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_contactChanging(int value);
    partial void Onid_contactChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnciviliteChanging(string value);
    partial void OnciviliteChanged();
    partial void OntelephoneChanging(System.Nullable<int> value);
    partial void OntelephoneChanged();
    partial void OnfaxChanging(System.Nullable<int> value);
    partial void OnfaxChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnfonctionChanging(string value);
    partial void OnfonctionChanged();
    partial void Onid_entrepriseChanging(System.Nullable<int> value);
    partial void Onid_entrepriseChanged();
    #endregion
	
	public Contact()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contact", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_contact
	{
		get
		{
			return this._id_contact;
		}
		set
		{
			if ((this._id_contact != value))
			{
				this.Onid_contactChanging(value);
				this.SendPropertyChanging();
				this._id_contact = value;
				this.SendPropertyChanged("id_contact");
				this.Onid_contactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(MAX)")]
	public string nom
	{
		get
		{
			return this._nom;
		}
		set
		{
			if ((this._nom != value))
			{
				this.OnnomChanging(value);
				this.SendPropertyChanging();
				this._nom = value;
				this.SendPropertyChanged("nom");
				this.OnnomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="NVarChar(MAX)")]
	public string prenom
	{
		get
		{
			return this._prenom;
		}
		set
		{
			if ((this._prenom != value))
			{
				this.OnprenomChanging(value);
				this.SendPropertyChanging();
				this._prenom = value;
				this.SendPropertyChanged("prenom");
				this.OnprenomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_civilite", DbType="NVarChar(MAX)")]
	public string civilite
	{
		get
		{
			return this._civilite;
		}
		set
		{
			if ((this._civilite != value))
			{
				this.OnciviliteChanging(value);
				this.SendPropertyChanging();
				this._civilite = value;
				this.SendPropertyChanged("civilite");
				this.OnciviliteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="Int")]
	public System.Nullable<int> telephone
	{
		get
		{
			return this._telephone;
		}
		set
		{
			if ((this._telephone != value))
			{
				this.OntelephoneChanging(value);
				this.SendPropertyChanging();
				this._telephone = value;
				this.SendPropertyChanged("telephone");
				this.OntelephoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="Int")]
	public System.Nullable<int> fax
	{
		get
		{
			return this._fax;
		}
		set
		{
			if ((this._fax != value))
			{
				this.OnfaxChanging(value);
				this.SendPropertyChanging();
				this._fax = value;
				this.SendPropertyChanged("fax");
				this.OnfaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(MAX)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fonction", DbType="NVarChar(MAX)")]
	public string fonction
	{
		get
		{
			return this._fonction;
		}
		set
		{
			if ((this._fonction != value))
			{
				this.OnfonctionChanging(value);
				this.SendPropertyChanging();
				this._fonction = value;
				this.SendPropertyChanged("fonction");
				this.OnfonctionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_entreprise", DbType="Int")]
	public System.Nullable<int> id_entreprise
	{
		get
		{
			return this._id_entreprise;
		}
		set
		{
			if ((this._id_entreprise != value))
			{
				this.Onid_entrepriseChanging(value);
				this.SendPropertyChanging();
				this._id_entreprise = value;
				this.SendPropertyChanged("id_entreprise");
				this.Onid_entrepriseChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class GetContactsByIDResult
{
	
	private int _id_contact;
	
	private string _nom;
	
	private string _prenom;
	
	private string _civilite;
	
	private System.Nullable<int> _telephone;
	
	private System.Nullable<int> _fax;
	
	private string _email;
	
	private string _fonction;
	
	private System.Nullable<int> _id_entreprise;
	
	public GetContactsByIDResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contact", DbType="Int NOT NULL")]
	public int id_contact
	{
		get
		{
			return this._id_contact;
		}
		set
		{
			if ((this._id_contact != value))
			{
				this._id_contact = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(MAX)")]
	public string nom
	{
		get
		{
			return this._nom;
		}
		set
		{
			if ((this._nom != value))
			{
				this._nom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="NVarChar(MAX)")]
	public string prenom
	{
		get
		{
			return this._prenom;
		}
		set
		{
			if ((this._prenom != value))
			{
				this._prenom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_civilite", DbType="NVarChar(MAX)")]
	public string civilite
	{
		get
		{
			return this._civilite;
		}
		set
		{
			if ((this._civilite != value))
			{
				this._civilite = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="Int")]
	public System.Nullable<int> telephone
	{
		get
		{
			return this._telephone;
		}
		set
		{
			if ((this._telephone != value))
			{
				this._telephone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="Int")]
	public System.Nullable<int> fax
	{
		get
		{
			return this._fax;
		}
		set
		{
			if ((this._fax != value))
			{
				this._fax = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(MAX)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fonction", DbType="NVarChar(MAX)")]
	public string fonction
	{
		get
		{
			return this._fonction;
		}
		set
		{
			if ((this._fonction != value))
			{
				this._fonction = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_entreprise", DbType="Int")]
	public System.Nullable<int> id_entreprise
	{
		get
		{
			return this._id_entreprise;
		}
		set
		{
			if ((this._id_entreprise != value))
			{
				this._id_entreprise = value;
			}
		}
	}
}

public partial class GetContactsByIDEntResult
{
	
	private int _id_contact;
	
	private string _nom;
	
	private string _prenom;
	
	private string _civilite;
	
	private System.Nullable<int> _telephone;
	
	private System.Nullable<int> _fax;
	
	private string _email;
	
	private string _fonction;
	
	private System.Nullable<int> _id_entreprise;
	
	public GetContactsByIDEntResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contact", DbType="Int NOT NULL")]
	public int id_contact
	{
		get
		{
			return this._id_contact;
		}
		set
		{
			if ((this._id_contact != value))
			{
				this._id_contact = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(MAX)")]
	public string nom
	{
		get
		{
			return this._nom;
		}
		set
		{
			if ((this._nom != value))
			{
				this._nom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="NVarChar(MAX)")]
	public string prenom
	{
		get
		{
			return this._prenom;
		}
		set
		{
			if ((this._prenom != value))
			{
				this._prenom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_civilite", DbType="NVarChar(MAX)")]
	public string civilite
	{
		get
		{
			return this._civilite;
		}
		set
		{
			if ((this._civilite != value))
			{
				this._civilite = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="Int")]
	public System.Nullable<int> telephone
	{
		get
		{
			return this._telephone;
		}
		set
		{
			if ((this._telephone != value))
			{
				this._telephone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="Int")]
	public System.Nullable<int> fax
	{
		get
		{
			return this._fax;
		}
		set
		{
			if ((this._fax != value))
			{
				this._fax = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(MAX)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fonction", DbType="NVarChar(MAX)")]
	public string fonction
	{
		get
		{
			return this._fonction;
		}
		set
		{
			if ((this._fonction != value))
			{
				this._fonction = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_entreprise", DbType="Int")]
	public System.Nullable<int> id_entreprise
	{
		get
		{
			return this._id_entreprise;
		}
		set
		{
			if ((this._id_entreprise != value))
			{
				this._id_entreprise = value;
			}
		}
	}
}

public partial class SelectContactsResult
{
	
	private int _id_contact;
	
	private string _nom;
	
	private string _prenom;
	
	private string _civilite;
	
	private System.Nullable<int> _telephone;
	
	private System.Nullable<int> _fax;
	
	private string _email;
	
	private string _fonction;
	
	private System.Nullable<int> _id_entreprise;
	
	public SelectContactsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contact", DbType="Int NOT NULL")]
	public int id_contact
	{
		get
		{
			return this._id_contact;
		}
		set
		{
			if ((this._id_contact != value))
			{
				this._id_contact = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(MAX)")]
	public string nom
	{
		get
		{
			return this._nom;
		}
		set
		{
			if ((this._nom != value))
			{
				this._nom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="NVarChar(MAX)")]
	public string prenom
	{
		get
		{
			return this._prenom;
		}
		set
		{
			if ((this._prenom != value))
			{
				this._prenom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_civilite", DbType="NVarChar(MAX)")]
	public string civilite
	{
		get
		{
			return this._civilite;
		}
		set
		{
			if ((this._civilite != value))
			{
				this._civilite = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="Int")]
	public System.Nullable<int> telephone
	{
		get
		{
			return this._telephone;
		}
		set
		{
			if ((this._telephone != value))
			{
				this._telephone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="Int")]
	public System.Nullable<int> fax
	{
		get
		{
			return this._fax;
		}
		set
		{
			if ((this._fax != value))
			{
				this._fax = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(MAX)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fonction", DbType="NVarChar(MAX)")]
	public string fonction
	{
		get
		{
			return this._fonction;
		}
		set
		{
			if ((this._fonction != value))
			{
				this._fonction = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_entreprise", DbType="Int")]
	public System.Nullable<int> id_entreprise
	{
		get
		{
			return this._id_entreprise;
		}
		set
		{
			if ((this._id_entreprise != value))
			{
				this._id_entreprise = value;
			}
		}
	}
}
#pragma warning restore 1591
