#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Erp")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Définitions de méthodes d'extensibilité
  partial void OnCreated();
  partial void InsertUtilisateur(Utilisateur instance);
  partial void UpdateUtilisateur(Utilisateur instance);
  partial void DeleteUtilisateur(Utilisateur instance);
  partial void InsertEntreprise(Entreprise instance);
  partial void UpdateEntreprise(Entreprise instance);
  partial void DeleteEntreprise(Entreprise instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ErpConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Utilisateur> Utilisateur
	{
		get
		{
			return this.GetTable<Utilisateur>();
		}
	}
	
	public System.Data.Linq.Table<Entreprise> Entreprise
	{
		get
		{
			return this.GetTable<Entreprise>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AjoutEntreprise")]
	public int AjoutEntreprise([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string ville, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string pays, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string adresse, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string adresse2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> code_postal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telephone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string site)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, ville, pays, adresse, adresse2, code_postal, telephone, fax, site);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteEntreprise")]
	public int DeleteEntreprise([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_entreprise)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_entreprise);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectEntreprises")]
	public ISingleResult<SelectEntreprisesResult> SelectEntreprises()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<SelectEntreprisesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateEntreprise")]
	public int UpdateEntreprise([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_entreprise, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string ville, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string pays, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string adresse, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string adresse2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> code_postal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telephone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string site)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_entreprise, nom, ville, pays, adresse, adresse2, code_postal, telephone, fax, site);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetEntreprisesByID")]
	public ISingleResult<GetEntreprisesByIDResult> GetEntreprisesByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_entreprise)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_entreprise);
		return ((ISingleResult<GetEntreprisesByIDResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateUtilistateur")]
	public int UpdateUtilistateur([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom", DbType="NVarChar(MAX)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(MAX)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(MAX)")] string password)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nom, email, password);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectUtilisateur")]
	public ISingleResult<SelectUtilisateurResult> SelectUtilisateur()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<SelectUtilisateurResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AjoutUtilisateur")]
	public int AjoutUtilisateur([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom", DbType="NVarChar(MAX)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(MAX)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(MAX)")] string password)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, email, password);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteUtilisateur")]
	public int DeleteUtilisateur([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Utilisateur")]
public partial class Utilisateur : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _Nom;
	
	private string _Email;
	
	private string _Password;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
	
	public Utilisateur()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(MAX)")]
	public string Nom
	{
		get
		{
			return this._Nom;
		}
		set
		{
			if ((this._Nom != value))
			{
				this.OnNomChanging(value);
				this.SendPropertyChanging();
				this._Nom = value;
				this.SendPropertyChanged("Nom");
				this.OnNomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entreprise")]
public partial class Entreprise : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_entreprise;
	
	private string _nom;
	
	private System.Nullable<int> _telephone;
	
	private System.Nullable<int> _fax;
	
	private string _site;
	
	private string _ville;
	
	private string _pays;
	
	private string _adresse;
	
	private string _adresse2;
	
	private System.Nullable<int> _code_postal;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_entrepriseChanging(int value);
    partial void Onid_entrepriseChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OntelephoneChanging(System.Nullable<int> value);
    partial void OntelephoneChanged();
    partial void OnfaxChanging(System.Nullable<int> value);
    partial void OnfaxChanged();
    partial void OnsiteChanging(string value);
    partial void OnsiteChanged();
    partial void OnvilleChanging(string value);
    partial void OnvilleChanged();
    partial void OnpaysChanging(string value);
    partial void OnpaysChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void Onadresse2Changing(string value);
    partial void Onadresse2Changed();
    partial void Oncode_postalChanging(System.Nullable<int> value);
    partial void Oncode_postalChanged();
    #endregion
	
	public Entreprise()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_entreprise", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_entreprise
	{
		get
		{
			return this._id_entreprise;
		}
		set
		{
			if ((this._id_entreprise != value))
			{
				this.Onid_entrepriseChanging(value);
				this.SendPropertyChanging();
				this._id_entreprise = value;
				this.SendPropertyChanged("id_entreprise");
				this.Onid_entrepriseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(MAX)")]
	public string nom
	{
		get
		{
			return this._nom;
		}
		set
		{
			if ((this._nom != value))
			{
				this.OnnomChanging(value);
				this.SendPropertyChanging();
				this._nom = value;
				this.SendPropertyChanged("nom");
				this.OnnomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="Int")]
	public System.Nullable<int> telephone
	{
		get
		{
			return this._telephone;
		}
		set
		{
			if ((this._telephone != value))
			{
				this.OntelephoneChanging(value);
				this.SendPropertyChanging();
				this._telephone = value;
				this.SendPropertyChanged("telephone");
				this.OntelephoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="Int")]
	public System.Nullable<int> fax
	{
		get
		{
			return this._fax;
		}
		set
		{
			if ((this._fax != value))
			{
				this.OnfaxChanging(value);
				this.SendPropertyChanging();
				this._fax = value;
				this.SendPropertyChanged("fax");
				this.OnfaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site", DbType="NVarChar(MAX)")]
	public string site
	{
		get
		{
			return this._site;
		}
		set
		{
			if ((this._site != value))
			{
				this.OnsiteChanging(value);
				this.SendPropertyChanging();
				this._site = value;
				this.SendPropertyChanged("site");
				this.OnsiteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ville", DbType="NVarChar(MAX)")]
	public string ville
	{
		get
		{
			return this._ville;
		}
		set
		{
			if ((this._ville != value))
			{
				this.OnvilleChanging(value);
				this.SendPropertyChanging();
				this._ville = value;
				this.SendPropertyChanged("ville");
				this.OnvilleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pays", DbType="NVarChar(MAX)")]
	public string pays
	{
		get
		{
			return this._pays;
		}
		set
		{
			if ((this._pays != value))
			{
				this.OnpaysChanging(value);
				this.SendPropertyChanging();
				this._pays = value;
				this.SendPropertyChanged("pays");
				this.OnpaysChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="NVarChar(MAX)")]
	public string adresse
	{
		get
		{
			return this._adresse;
		}
		set
		{
			if ((this._adresse != value))
			{
				this.OnadresseChanging(value);
				this.SendPropertyChanging();
				this._adresse = value;
				this.SendPropertyChanged("adresse");
				this.OnadresseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse2", DbType="NVarChar(MAX)")]
	public string adresse2
	{
		get
		{
			return this._adresse2;
		}
		set
		{
			if ((this._adresse2 != value))
			{
				this.Onadresse2Changing(value);
				this.SendPropertyChanging();
				this._adresse2 = value;
				this.SendPropertyChanged("adresse2");
				this.Onadresse2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_postal", DbType="Int")]
	public System.Nullable<int> code_postal
	{
		get
		{
			return this._code_postal;
		}
		set
		{
			if ((this._code_postal != value))
			{
				this.Oncode_postalChanging(value);
				this.SendPropertyChanging();
				this._code_postal = value;
				this.SendPropertyChanged("code_postal");
				this.Oncode_postalChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class SelectEntreprisesResult
{
	
	private int _id_entreprise;
	
	private string _nom;
	
	private System.Nullable<int> _telephone;
	
	private System.Nullable<int> _fax;
	
	private string _site;
	
	private string _ville;
	
	private string _pays;
	
	private string _adresse;
	
	private string _adresse2;
	
	private System.Nullable<int> _code_postal;
	
	public SelectEntreprisesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_entreprise", DbType="Int NOT NULL")]
	public int id_entreprise
	{
		get
		{
			return this._id_entreprise;
		}
		set
		{
			if ((this._id_entreprise != value))
			{
				this._id_entreprise = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(MAX)")]
	public string nom
	{
		get
		{
			return this._nom;
		}
		set
		{
			if ((this._nom != value))
			{
				this._nom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="Int")]
	public System.Nullable<int> telephone
	{
		get
		{
			return this._telephone;
		}
		set
		{
			if ((this._telephone != value))
			{
				this._telephone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="Int")]
	public System.Nullable<int> fax
	{
		get
		{
			return this._fax;
		}
		set
		{
			if ((this._fax != value))
			{
				this._fax = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site", DbType="NVarChar(MAX)")]
	public string site
	{
		get
		{
			return this._site;
		}
		set
		{
			if ((this._site != value))
			{
				this._site = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ville", DbType="NVarChar(MAX)")]
	public string ville
	{
		get
		{
			return this._ville;
		}
		set
		{
			if ((this._ville != value))
			{
				this._ville = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pays", DbType="NVarChar(MAX)")]
	public string pays
	{
		get
		{
			return this._pays;
		}
		set
		{
			if ((this._pays != value))
			{
				this._pays = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="NVarChar(MAX)")]
	public string adresse
	{
		get
		{
			return this._adresse;
		}
		set
		{
			if ((this._adresse != value))
			{
				this._adresse = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse2", DbType="NVarChar(MAX)")]
	public string adresse2
	{
		get
		{
			return this._adresse2;
		}
		set
		{
			if ((this._adresse2 != value))
			{
				this._adresse2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_postal", DbType="Int")]
	public System.Nullable<int> code_postal
	{
		get
		{
			return this._code_postal;
		}
		set
		{
			if ((this._code_postal != value))
			{
				this._code_postal = value;
			}
		}
	}
}

public partial class GetEntreprisesByIDResult
{
	
	private int _id_entreprise;
	
	private string _nom;
	
	private System.Nullable<int> _telephone;
	
	private System.Nullable<int> _fax;
	
	private string _site;
	
	private string _ville;
	
	private string _pays;
	
	private string _adresse;
	
	private string _adresse2;
	
	private System.Nullable<int> _code_postal;
	
	public GetEntreprisesByIDResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_entreprise", DbType="Int NOT NULL")]
	public int id_entreprise
	{
		get
		{
			return this._id_entreprise;
		}
		set
		{
			if ((this._id_entreprise != value))
			{
				this._id_entreprise = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(MAX)")]
	public string nom
	{
		get
		{
			return this._nom;
		}
		set
		{
			if ((this._nom != value))
			{
				this._nom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="Int")]
	public System.Nullable<int> telephone
	{
		get
		{
			return this._telephone;
		}
		set
		{
			if ((this._telephone != value))
			{
				this._telephone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="Int")]
	public System.Nullable<int> fax
	{
		get
		{
			return this._fax;
		}
		set
		{
			if ((this._fax != value))
			{
				this._fax = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site", DbType="NVarChar(MAX)")]
	public string site
	{
		get
		{
			return this._site;
		}
		set
		{
			if ((this._site != value))
			{
				this._site = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ville", DbType="NVarChar(MAX)")]
	public string ville
	{
		get
		{
			return this._ville;
		}
		set
		{
			if ((this._ville != value))
			{
				this._ville = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pays", DbType="NVarChar(MAX)")]
	public string pays
	{
		get
		{
			return this._pays;
		}
		set
		{
			if ((this._pays != value))
			{
				this._pays = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="NVarChar(MAX)")]
	public string adresse
	{
		get
		{
			return this._adresse;
		}
		set
		{
			if ((this._adresse != value))
			{
				this._adresse = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse2", DbType="NVarChar(MAX)")]
	public string adresse2
	{
		get
		{
			return this._adresse2;
		}
		set
		{
			if ((this._adresse2 != value))
			{
				this._adresse2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_postal", DbType="Int")]
	public System.Nullable<int> code_postal
	{
		get
		{
			return this._code_postal;
		}
		set
		{
			if ((this._code_postal != value))
			{
				this._code_postal = value;
			}
		}
	}
}

public partial class SelectUtilisateurResult
{
	
	private int _id;
	
	private string _Nom;
	
	private string _Email;
	
	private string _Password;
	
	public SelectUtilisateurResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(MAX)")]
	public string Nom
	{
		get
		{
			return this._Nom;
		}
		set
		{
			if ((this._Nom != value))
			{
				this._Nom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this._Password = value;
			}
		}
	}
}
#pragma warning restore 1591
