#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Erp")]
public partial class DataClasses2DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Définitions de méthodes d'extensibilité
  partial void OnCreated();
  partial void InsertEvent(Event instance);
  partial void UpdateEvent(Event instance);
  partial void DeleteEvent(Event instance);
  #endregion
	
	public DataClasses2DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ErpConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Event> Event
	{
		get
		{
			return this.GetTable<Event>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteEvents")]
	public int DeleteEvents([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_event)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_event);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectEvents")]
	public ISingleResult<SelectEventsResult> SelectEvents()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<SelectEventsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AjouterEvent")]
	public int AjouterEvent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string objet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date_debut, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date_fin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> heure_debut, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> heure_fin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string attribu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string lieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_utilisateur, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_contact)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), type, objet, date_debut, date_fin, heure_debut, heure_fin, attribu, description, lieu, id_utilisateur, id_contact);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateEvents")]
	public int UpdateEvents([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_event, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string objet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date_debut, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date_fin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> heure_debut, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> heure_fin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string attribu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string lieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_utilisateur, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_contact)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_event, type, objet, date_debut, date_fin, heure_debut, heure_fin, attribu, description, lieu, id_utilisateur, id_contact);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetEventByIDContact")]
	public ISingleResult<GetEventByIDContactResult> GetEventByIDContact([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_contact)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_contact);
		return ((ISingleResult<GetEventByIDContactResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Event")]
public partial class Event : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_event;
	
	private string _type;
	
	private string _objet;
	
	private System.Nullable<System.DateTime> _date_debut;
	
	private System.Nullable<System.DateTime> _date_fin;
	
	private System.Nullable<System.TimeSpan> _heure_debut;
	
	private System.Nullable<System.TimeSpan> _heure_fin;
	
	private string _attribu;
	
	private string _description;
	
	private string _lieu;
	
	private System.Nullable<int> _id_utilisateur;
	
	private System.Nullable<int> _id_contact;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_eventChanging(int value);
    partial void Onid_eventChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnobjetChanging(string value);
    partial void OnobjetChanged();
    partial void Ondate_debutChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_debutChanged();
    partial void Ondate_finChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_finChanged();
    partial void Onheure_debutChanging(System.Nullable<System.TimeSpan> value);
    partial void Onheure_debutChanged();
    partial void Onheure_finChanging(System.Nullable<System.TimeSpan> value);
    partial void Onheure_finChanged();
    partial void OnattribuChanging(string value);
    partial void OnattribuChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnlieuChanging(string value);
    partial void OnlieuChanged();
    partial void Onid_utilisateurChanging(System.Nullable<int> value);
    partial void Onid_utilisateurChanged();
    partial void Onid_contactChanging(System.Nullable<int> value);
    partial void Onid_contactChanged();
    #endregion
	
	public Event()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_event", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_event
	{
		get
		{
			return this._id_event;
		}
		set
		{
			if ((this._id_event != value))
			{
				this.Onid_eventChanging(value);
				this.SendPropertyChanging();
				this._id_event = value;
				this.SendPropertyChanged("id_event");
				this.Onid_eventChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(MAX)")]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objet", DbType="NVarChar(MAX)")]
	public string objet
	{
		get
		{
			return this._objet;
		}
		set
		{
			if ((this._objet != value))
			{
				this.OnobjetChanging(value);
				this.SendPropertyChanging();
				this._objet = value;
				this.SendPropertyChanged("objet");
				this.OnobjetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_debut", DbType="DateTime")]
	public System.Nullable<System.DateTime> date_debut
	{
		get
		{
			return this._date_debut;
		}
		set
		{
			if ((this._date_debut != value))
			{
				this.Ondate_debutChanging(value);
				this.SendPropertyChanging();
				this._date_debut = value;
				this.SendPropertyChanged("date_debut");
				this.Ondate_debutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_fin", DbType="DateTime")]
	public System.Nullable<System.DateTime> date_fin
	{
		get
		{
			return this._date_fin;
		}
		set
		{
			if ((this._date_fin != value))
			{
				this.Ondate_finChanging(value);
				this.SendPropertyChanging();
				this._date_fin = value;
				this.SendPropertyChanged("date_fin");
				this.Ondate_finChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heure_debut", DbType="Time")]
	public System.Nullable<System.TimeSpan> heure_debut
	{
		get
		{
			return this._heure_debut;
		}
		set
		{
			if ((this._heure_debut != value))
			{
				this.Onheure_debutChanging(value);
				this.SendPropertyChanging();
				this._heure_debut = value;
				this.SendPropertyChanged("heure_debut");
				this.Onheure_debutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heure_fin", DbType="Time")]
	public System.Nullable<System.TimeSpan> heure_fin
	{
		get
		{
			return this._heure_fin;
		}
		set
		{
			if ((this._heure_fin != value))
			{
				this.Onheure_finChanging(value);
				this.SendPropertyChanging();
				this._heure_fin = value;
				this.SendPropertyChanged("heure_fin");
				this.Onheure_finChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attribu", DbType="NVarChar(MAX)")]
	public string attribu
	{
		get
		{
			return this._attribu;
		}
		set
		{
			if ((this._attribu != value))
			{
				this.OnattribuChanging(value);
				this.SendPropertyChanging();
				this._attribu = value;
				this.SendPropertyChanged("attribu");
				this.OnattribuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieu", DbType="NVarChar(MAX)")]
	public string lieu
	{
		get
		{
			return this._lieu;
		}
		set
		{
			if ((this._lieu != value))
			{
				this.OnlieuChanging(value);
				this.SendPropertyChanging();
				this._lieu = value;
				this.SendPropertyChanged("lieu");
				this.OnlieuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_utilisateur", DbType="Int")]
	public System.Nullable<int> id_utilisateur
	{
		get
		{
			return this._id_utilisateur;
		}
		set
		{
			if ((this._id_utilisateur != value))
			{
				this.Onid_utilisateurChanging(value);
				this.SendPropertyChanging();
				this._id_utilisateur = value;
				this.SendPropertyChanged("id_utilisateur");
				this.Onid_utilisateurChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contact", DbType="Int")]
	public System.Nullable<int> id_contact
	{
		get
		{
			return this._id_contact;
		}
		set
		{
			if ((this._id_contact != value))
			{
				this.Onid_contactChanging(value);
				this.SendPropertyChanging();
				this._id_contact = value;
				this.SendPropertyChanged("id_contact");
				this.Onid_contactChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class SelectEventsResult
{
	
	private int _id_event;
	
	private string _type;
	
	private string _objet;
	
	private System.Nullable<System.DateTime> _date_debut;
	
	private System.Nullable<System.DateTime> _date_fin;
	
	private System.Nullable<System.TimeSpan> _heure_debut;
	
	private System.Nullable<System.TimeSpan> _heure_fin;
	
	private string _attribu;
	
	private string _description;
	
	private string _lieu;
	
	private System.Nullable<int> _id_contact;
	
	public SelectEventsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_event", DbType="Int NOT NULL")]
	public int id_event
	{
		get
		{
			return this._id_event;
		}
		set
		{
			if ((this._id_event != value))
			{
				this._id_event = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(MAX)")]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this._type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objet", DbType="NVarChar(MAX)")]
	public string objet
	{
		get
		{
			return this._objet;
		}
		set
		{
			if ((this._objet != value))
			{
				this._objet = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_debut", DbType="DateTime")]
	public System.Nullable<System.DateTime> date_debut
	{
		get
		{
			return this._date_debut;
		}
		set
		{
			if ((this._date_debut != value))
			{
				this._date_debut = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_fin", DbType="DateTime")]
	public System.Nullable<System.DateTime> date_fin
	{
		get
		{
			return this._date_fin;
		}
		set
		{
			if ((this._date_fin != value))
			{
				this._date_fin = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heure_debut", DbType="Time")]
	public System.Nullable<System.TimeSpan> heure_debut
	{
		get
		{
			return this._heure_debut;
		}
		set
		{
			if ((this._heure_debut != value))
			{
				this._heure_debut = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heure_fin", DbType="Time")]
	public System.Nullable<System.TimeSpan> heure_fin
	{
		get
		{
			return this._heure_fin;
		}
		set
		{
			if ((this._heure_fin != value))
			{
				this._heure_fin = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attribu", DbType="NVarChar(MAX)")]
	public string attribu
	{
		get
		{
			return this._attribu;
		}
		set
		{
			if ((this._attribu != value))
			{
				this._attribu = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this._description = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieu", DbType="NVarChar(MAX)")]
	public string lieu
	{
		get
		{
			return this._lieu;
		}
		set
		{
			if ((this._lieu != value))
			{
				this._lieu = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contact", DbType="Int")]
	public System.Nullable<int> id_contact
	{
		get
		{
			return this._id_contact;
		}
		set
		{
			if ((this._id_contact != value))
			{
				this._id_contact = value;
			}
		}
	}
}

public partial class GetEventByIDContactResult
{
	
	private int _id_event;
	
	private string _type;
	
	private string _objet;
	
	private System.Nullable<System.DateTime> _date_debut;
	
	private System.Nullable<System.DateTime> _date_fin;
	
	private System.Nullable<System.TimeSpan> _heure_debut;
	
	private System.Nullable<System.TimeSpan> _heure_fin;
	
	private string _attribu;
	
	private string _description;
	
	private string _lieu;
	
	private System.Nullable<int> _id_utilisateur;
	
	private System.Nullable<int> _id_contact;
	
	public GetEventByIDContactResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_event", DbType="Int NOT NULL")]
	public int id_event
	{
		get
		{
			return this._id_event;
		}
		set
		{
			if ((this._id_event != value))
			{
				this._id_event = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(MAX)")]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this._type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objet", DbType="NVarChar(MAX)")]
	public string objet
	{
		get
		{
			return this._objet;
		}
		set
		{
			if ((this._objet != value))
			{
				this._objet = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_debut", DbType="DateTime")]
	public System.Nullable<System.DateTime> date_debut
	{
		get
		{
			return this._date_debut;
		}
		set
		{
			if ((this._date_debut != value))
			{
				this._date_debut = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_fin", DbType="DateTime")]
	public System.Nullable<System.DateTime> date_fin
	{
		get
		{
			return this._date_fin;
		}
		set
		{
			if ((this._date_fin != value))
			{
				this._date_fin = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heure_debut", DbType="Time")]
	public System.Nullable<System.TimeSpan> heure_debut
	{
		get
		{
			return this._heure_debut;
		}
		set
		{
			if ((this._heure_debut != value))
			{
				this._heure_debut = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heure_fin", DbType="Time")]
	public System.Nullable<System.TimeSpan> heure_fin
	{
		get
		{
			return this._heure_fin;
		}
		set
		{
			if ((this._heure_fin != value))
			{
				this._heure_fin = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attribu", DbType="NVarChar(MAX)")]
	public string attribu
	{
		get
		{
			return this._attribu;
		}
		set
		{
			if ((this._attribu != value))
			{
				this._attribu = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this._description = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieu", DbType="NVarChar(MAX)")]
	public string lieu
	{
		get
		{
			return this._lieu;
		}
		set
		{
			if ((this._lieu != value))
			{
				this._lieu = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_utilisateur", DbType="Int")]
	public System.Nullable<int> id_utilisateur
	{
		get
		{
			return this._id_utilisateur;
		}
		set
		{
			if ((this._id_utilisateur != value))
			{
				this._id_utilisateur = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contact", DbType="Int")]
	public System.Nullable<int> id_contact
	{
		get
		{
			return this._id_contact;
		}
		set
		{
			if ((this._id_contact != value))
			{
				this._id_contact = value;
			}
		}
	}
}
#pragma warning restore 1591
